require("utility.lists.style-data").GeneratePrototypes()
require("prototypes.recruit-team-member")
require("prototypes.shortcuts")
require("prototypes.explosive-delivery")
require("prototypes.invisible-blockers")
