-- Alien Biomes - 0.6.1
local Data = {}

Data.GetTileData = function()
    return {
        ["frozen-snow-0"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-1"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-2"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-3"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-4"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-5"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-6"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-7"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-8"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-9"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["mineral-aubergine-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-aubergine-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-aubergine-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.8
                }
            }
        },
        ["mineral-aubergine-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.95
                }
            }
        },
        ["mineral-aubergine-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-aubergine-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-aubergine-sand-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-aubergine-sand-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-aubergine-sand-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-beige-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-beige-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-beige-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.8
                }
            }
        },
        ["mineral-beige-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.95
                }
            }
        },
        ["mineral-beige-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-beige-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-beige-sand-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-beige-sand-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-beige-sand-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-black-dirt-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-black-dirt-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-black-dirt-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.8
                }
            }
        },
        ["mineral-black-dirt-4"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.95
                }
            }
        },
        ["mineral-black-dirt-5"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-black-dirt-6"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-black-sand-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["mineral-black-sand-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["mineral-black-sand-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["mineral-brown-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-brown-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-brown-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            }
        },
        ["mineral-brown-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            }
        },
        ["mineral-brown-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-brown-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-brown-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-brown-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-brown-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-cream-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-cream-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-cream-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.8
                }
            }
        },
        ["mineral-cream-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.95
                }
            }
        },
        ["mineral-cream-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-cream-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-cream-sand-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-cream-sand-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-cream-sand-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-dustyrose-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-dustyrose-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-dustyrose-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.8
                }
            }
        },
        ["mineral-dustyrose-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.95
                }
            }
        },
        ["mineral-dustyrose-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-dustyrose-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            }
        },
        ["mineral-dustyrose-sand-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-dustyrose-sand-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-dustyrose-sand-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            }
        },
        ["mineral-grey-dirt-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-grey-dirt-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-grey-dirt-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.8
                }
            }
        },
        ["mineral-grey-dirt-4"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.95
                }
            }
        },
        ["mineral-grey-dirt-5"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-grey-dirt-6"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-grey-sand-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["mineral-grey-sand-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["mineral-grey-sand-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["mineral-purple-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-purple-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-purple-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            }
        },
        ["mineral-purple-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            }
        },
        ["mineral-purple-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-purple-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-purple-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-purple-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-purple-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-red-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-red-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-red-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            }
        },
        ["mineral-red-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            }
        },
        ["mineral-red-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-red-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-red-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-red-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-red-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-tan-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-tan-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-tan-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            }
        },
        ["mineral-tan-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            }
        },
        ["mineral-tan-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-tan-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-tan-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-tan-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-tan-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-violet-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-violet-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-violet-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            }
        },
        ["mineral-violet-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            }
        },
        ["mineral-violet-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-violet-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            }
        },
        ["mineral-violet-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-violet-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-violet-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            }
        },
        ["mineral-white-dirt-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-white-dirt-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-white-dirt-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.8
                }
            }
        },
        ["mineral-white-dirt-4"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.95
                }
            }
        },
        ["mineral-white-dirt-5"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-white-dirt-6"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            }
        },
        ["mineral-white-sand-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["mineral-white-sand-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["mineral-white-sand-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            }
        },
        ["vegetation-blue-grass-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.2,
                    1
                }
            }
        },
        ["vegetation-blue-grass-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.2,
                    1
                }
            }
        },
        ["vegetation-green-grass-1"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.5,
                    1
                }
            }
        },
        ["vegetation-green-grass-2"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.5,
                    1
                }
            }
        },
        ["vegetation-green-grass-3"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.5,
                    1
                }
            }
        },
        ["vegetation-green-grass-4"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.5,
                    1
                }
            }
        },
        ["vegetation-mauve-grass-1"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.4,
                    1
                }
            }
        },
        ["vegetation-mauve-grass-2"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.4,
                    1
                }
            }
        },
        ["vegetation-olive-grass-1"] = {
            "allow-trees",
            {
                {
                    0.5,
                    0.6
                },
                {
                    0.65,
                    1
                }
            }
        },
        ["vegetation-olive-grass-2"] = {
            "allow-trees",
            {
                {
                    0.5,
                    0.6
                },
                {
                    0.65,
                    1
                }
            }
        },
        ["vegetation-orange-grass-1"] = {
            "allow-trees",
            {
                {
                    0.8,
                    0.6
                },
                {
                    1,
                    1
                }
            }
        },
        ["vegetation-orange-grass-2"] = {
            "allow-trees",
            {
                {
                    0.8,
                    0.6
                },
                {
                    1,
                    1
                }
            }
        },
        ["vegetation-purple-grass-1"] = {
            "allow-trees",
            {
                {
                    0.4,
                    0.6
                },
                {
                    0.6,
                    1
                }
            }
        },
        ["vegetation-purple-grass-2"] = {
            "allow-trees",
            {
                {
                    0.4,
                    0.6
                },
                {
                    0.6,
                    1
                }
            }
        },
        ["vegetation-red-grass-1"] = {
            "allow-trees",
            {
                {
                    0.8,
                    0.6
                },
                {
                    1,
                    1
                }
            }
        },
        ["vegetation-red-grass-2"] = {
            "allow-trees",
            {
                {
                    0.8,
                    0.6
                },
                {
                    1,
                    1
                }
            }
        },
        ["vegetation-turquoise-grass-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.2,
                    1
                }
            }
        },
        ["vegetation-turquoise-grass-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.2,
                    1
                }
            }
        },
        ["vegetation-violet-grass-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    0.8,
                    1
                }
            }
        },
        ["vegetation-violet-grass-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    0.8,
                    1
                }
            }
        },
        ["vegetation-yellow-grass-1"] = {
            "allow-trees",
            {
                {
                    0.65,
                    0.6
                },
                {
                    0.8,
                    1
                }
            }
        },
        ["vegetation-yellow-grass-2"] = {
            "allow-trees",
            {
                {
                    0.65,
                    0.6
                },
                {
                    0.8,
                    1
                }
            }
        },
        ["volcanic-blue-heat-1"] = {
            "allow-trees",
            {
                {
                    1
                },
                {
                    1.2
                }
            }
        },
        ["volcanic-blue-heat-2"] = {
            "allow-trees",
            {
                {
                    1.2
                },
                {
                    1.3500000000000001
                }
            }
        },
        ["volcanic-blue-heat-3"] = {
            "allow-trees",
            {
                {
                    1.3500000000000001
                },
                {
                    1.45
                }
            }
        },
        ["volcanic-blue-heat-4"] = {
            "allow-trees",
            {
                {
                    1.45
                },
                {
                    1.5
                }
            }
        },
        ["volcanic-green-heat-1"] = {
            "allow-trees",
            {
                {
                    1
                },
                {
                    1.2
                }
            }
        },
        ["volcanic-green-heat-2"] = {
            "allow-trees",
            {
                {
                    1.2
                },
                {
                    1.3500000000000001
                }
            }
        },
        ["volcanic-green-heat-3"] = {
            "allow-trees",
            {
                {
                    1.3500000000000001
                },
                {
                    1.45
                }
            }
        },
        ["volcanic-green-heat-4"] = {
            "allow-trees",
            {
                {
                    1.45
                },
                {
                    1.5
                }
            }
        },
        ["volcanic-orange-heat-1"] = {
            "allow-trees",
            {
                {
                    1
                },
                {
                    1.2
                }
            }
        },
        ["volcanic-orange-heat-2"] = {
            "allow-trees",
            {
                {
                    1.2
                },
                {
                    1.3500000000000001
                }
            }
        },
        ["volcanic-orange-heat-3"] = {
            "allow-trees",
            {
                {
                    1.3500000000000001
                },
                {
                    1.45
                }
            }
        },
        ["volcanic-orange-heat-4"] = {
            "allow-trees",
            {
                {
                    1.45
                },
                {
                    1.5
                }
            }
        },
        ["volcanic-purple-heat-1"] = {
            "allow-trees",
            {
                {
                    1
                },
                {
                    1.2
                }
            }
        },
        ["volcanic-purple-heat-2"] = {
            "allow-trees",
            {
                {
                    1.2
                },
                {
                    1.3500000000000001
                }
            }
        },
        ["volcanic-purple-heat-3"] = {
            "allow-trees",
            {
                {
                    1.3500000000000001
                },
                {
                    1.45
                }
            }
        },
        ["volcanic-purple-heat-4"] = {
            "allow-trees",
            {
                {
                    1.45
                },
                {
                    1.5
                }
            }
        }
    }
end

return Data
